spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subfootball_tracker
    username: subfootball_tracker_user
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml