spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/subfootball_tracker}
    username: ${DATABASE_USERNAME:subfootball_tracker_user}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: false

email:
  sender-address: subfootball-tracker@jordansimsmith.com
  sender-name: SUB Football Tracker
  content-change-template-id: d-310b3df757dc4b73ad037618c91ea7e2
  send-grid-api-key: ${SEND_GRID_API_KEY}
  subscribers:
    - name: Jordan
      email: jordansimsmith@gmail.com